#include "recon/Io.hpp"

#include <algorithm>
#include <cctype>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <stdexcept>

namespace recon {
namespace {

// Extrae todos los grupos de digitos de un nombre y los devuelve como numeros.
// "cloud_1583836591_182590976.pcd" -> {1583836591, 182590976}
std::vector<std::uint64_t> ExtractNumbers(const std::string& name) {
    std::vector<std::uint64_t> nums;
    std::size_t i = 0;
    while (i < name.size()) {
        if (std::isdigit(static_cast<unsigned char>(name[i]))) {
            std::uint64_t value = 0;
            while (i < name.size() && std::isdigit(static_cast<unsigned char>(name[i]))) {
                // Saturacion defensiva por si aparece un numero absurdamente largo.
                if (value < 1000000000000000000ULL) {
                    value = value * 10 + static_cast<std::uint64_t>(name[i] - '0');
                }
                ++i;
            }
            nums.push_back(value);
        } else {
            ++i;
        }
    }
    return nums;
}

}  // namespace

std::vector<std::string> ListScansSorted(const std::string& directory) {
    namespace fs = std::filesystem;
    if (!fs::exists(directory) || !fs::is_directory(directory)) {
        throw std::runtime_error("El directorio de scans no existe: " + directory);
    }

    struct Entry {
        std::string path;
        std::vector<std::uint64_t> key;
    };

    std::vector<Entry> entries;
    for (const auto& item : fs::directory_iterator(directory)) {
        if (!item.is_regular_file()) continue;
        if (item.path().extension() != ".pcd") continue;
        entries.push_back({item.path().string(), ExtractNumbers(item.path().stem().string())});
    }

    // Comparacion lexicografica sobre la secuencia de numeros: primero los
    // segundos, luego los nanosegundos. Si un nombre no trae numeros, cae al
    // final ordenado por ruta.
    std::sort(entries.begin(), entries.end(), [](const Entry& a, const Entry& b) {
        if (a.key.empty() || b.key.empty()) return a.path < b.path;
        if (a.key != b.key) return a.key < b.key;
        return a.path < b.path;
    });

    std::vector<std::string> paths;
    paths.reserve(entries.size());
    for (auto& e : entries) paths.push_back(std::move(e.path));
    return paths;
}

void WritePly(const std::string& path,
              const std::vector<Eigen::Vector3d>& vertices,
              const std::vector<Eigen::Vector3i>& triangles) {
    std::ofstream out(path);
    if (!out) throw std::runtime_error("No se pudo escribir el PLY: " + path);

    out << "ply\n"
        << "format ascii 1.0\n"
        << "comment generated by recon (EL5859 ITCR)\n"
        << "element vertex " << vertices.size() << "\n"
        << "property float x\n"
        << "property float y\n"
        << "property float z\n"
        << "element face " << triangles.size() << "\n"
        << "property list uchar int vertex_index\n"
        << "end_header\n";

    for (const auto& v : vertices) {
        out << v.x() << " " << v.y() << " " << v.z() << "\n";
    }
    for (const auto& t : triangles) {
        out << "3 " << t.x() << " " << t.y() << " " << t.z() << "\n";
    }
}

}  // namespace recon
